### ISSUE TITLE
Typo in readme.md file.

### ISSUE THREAD

**Issue by Sanjuhub** [Nikhil-Kumaran/reactjs-boilerplate#15]
There should not instead of hot in highlighted line.

The page will ![git](https://user-images.githubusercontent.com/20820156/120109536-7275ca80-c187-11eb-9cc5-e9b76c353276.PNG) reload if you make edits.

**Comment by Nikhil-Kumaran** [comment]
That's not a typo @Sanjuhub It's instant reloading on save is called "hot" reloading.

**Comment by Sanjuhub** [comment]
Okay, I got it. Thanks a lot.
