### ISSUE TITLE
Can't resolve .jsx

### ISSUE THREAD

**Issue by wickedest** [Nikhil-Kumaran/reactjs-boilerplate#5]
@Nikhil-Kumaran, thanks for the boilerplate - I'm checking it out today and I like what I see so far (clean, crisp, useful).  I prefer jsx so I renamed `App.js` to `App.jsx`, and get the error:
```
ERROR in ./src/index.js
Module not found: Error: Can't resolve './App' in '/home/jamie/websites/goilin/react-app/src'
 @ ./src/index.js 7:0-24 8:50-53
 @ multi react-hot-loader/patch ./src
```
I found that webpack was not configured to [resolve](https://webpack.js.org/configuration/resolve/#resolveextensions) the extension.  Adding `extensions` to `webpack.config.js` seemed to fix the problem:
```js
  resolve: {
    extensions: ['.js', '.jsx'],
    modules: [path.join(__dirname, 'src'), 'node_modules'],
    alias: {
      react: path.join(__dirname, 'node_modules', 'react'),
    },
  },
```

**Comment by Nikhil-Kumaran** [comment]
Hey @wickedest Thanks for using the boilerplate. 

Thanks for raising the issue. Will you be able to make a PR and add the fix?

**Comment by anshul2807** [comment]
I have Raised the PR.

**Comment by Nikhil-Kumaran** [comment]
Closing this as it's resolved
